repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args: ["--strict"]
        additional_dependencies: ["pydantic-settings"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", "src/gaij"]
  - repo: local
    hooks:
      - id: radon
        name: radon
        entry: radon
        language: system
        args: ["cc", "src/gaij", "-s", "--fail", "B"]
