version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./token.json:/app/token.json:ro
      - ./client_secret.json:/app/client_secret.json:ro
      - app-data:/data
    command: python main.py

volumes:
  app-data:
