version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./token.json:/app/token.json:ro
      - ./logs:/data
    command: python main.py
