name: Test and Deploy to Cloud Run

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ruff
        run: ruff check --select I,UP,B,C4,SIM,N,RUF --fix .

      - name: Mypy
        run: mypy --strict src/gaij

      - name: Bandit
        run: bandit -r src/gaij

      - name: Radon
        run: |
          radon cc src/gaij -s -n C | tee /tmp/radon.txt
          test ! -s /tmp/radon.txt

      - name: Pytest
        run: pytest -q --cov=gaij --cov-fail-under=90

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run (build from source)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service:    ${{ secrets.CLOUD_RUN_SERVICE }}    # e.g. g-ai-j
          region:     ${{ secrets.GCP_REGION }}           # e.g. europe-central2
          project_id: ${{ secrets.GCP_PROJECT_ID }}       # e.g. gmail-ai-jira
          source: .
          flags: >
            --service-account=${{ secrets.RUNTIME_SA }}
            --build-service-account=${{ secrets.BUILD_SA }}
            --allow-unauthenticated
